name: RDP-Tailscale-NRA-Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: 1. Cau hinh Windows & User
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          
          $username = "RDP"
          $password = "Oibanoi874@" 
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) { Remove-LocalUser -Name $username }
          New-LocalUser -Name $username -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Restart-Service -Name TermService -Force

      - name: 2. Cai dat & Ket noi Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-game-runner
          
          $tsIP = ""
          for ($i=0; $i -lt 12; $i++) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              if ($tsIP) { break }
              Start-Sleep -Seconds 5
          }
          
          Write-Host "IP CUA BAN: $tsIP"
          echo "TS_IP=$tsIP" >> $env:GITHUB_ENV

      - name: 3. Tai Game bang wget ra Desktop
        run: |
          # Duong dan den Desktop cua User RDP
          $desktopPath = "C:\Users\RDP\Desktop"
          
          # Tao thu muc Desktop neu chua co (de phong)
          if (!(Test-Path $desktopPath)) { New-Item -ItemType Directory -Path $desktopPath }
          
          $url = "https://rescdnft97vn.xfplayvn.com/apk/NgocRongAwakenver228.exe"
          $fileName = "NgocRongAwaken.exe"
          $fullPath = Join-Path $desktopPath $fileName
          
          Write-Host "Dang tai game ra Desktop..."
          # Su dung wget (alias cua Invoke-WebRequest trong PowerShell)
          wget -Uri $url -OutFile $fullPath -UseBasicParsing
          
          Write-Host "File da nam o: $fullPath"

      - name: 4. Duy tri may ao
        run: |
          Write-Host "Login RDP: $env:TS_IP | User: RDP | Pass: Oibanoi874@"
          while ($true) {
              $date = Get-Date -Format "HH:mm:ss"
              Write-Host "[$date] Dang treo may..."
              Start-Sleep -Seconds 300
          }
